Task 7 fix
artmotika/formal-lang-course pull request #11
Opened 2022-11-03 21:51 UTC by artmotika

# Задача 7. Рекурсивные конечные автоматы

* **Мягкий дедлайн**: 24.10.2021, 23:59
* **Жёсткий дедлайн**: 27.10.2021, 23:59
* Полный балл: 5

## Расширенные контекстно-свободные грамматики (ECFG)

В дополнение к существующему в pyformalng формату описания КС грамматик зафиксируем следующий формат.
- Для каждого нетерминала существует ровно одно правило.
- На одной строке содержится ровно одно правило.
- Правило --- это нетерминал и регулярное выражение над терминалами и нетерминалами, принимаемое pyformalng, разделенные ``` -> ```. Например: ``` S -> a | b* S ```

Будем называть данный формат расширенными контекстно-свободными грамматиками (Extended Context-Free Grammars, ECFG).

## Задача

- [x] Реализовать тип для представления рекурсивных конечных автоматов. В качестве составных частей можно использовать типы из pyformlang (например, [конечные автоматы](https://pyformlang.readthedocs.io/en/latest/usage.html#finite-automata)). При проектировании этого типа необходимо помнить, что рекурсивные конечные автоматы будут использоваться в алгоритмах КС достижимости, основанных на линейной алгебре, а значит необходимо будет строить матрицы смежности. Здесь могут быть полезны результаты домашних работ по конечным автоматам.
- [x] Реализовать внутреннее представление для ECFG, пригодное как для дальнейшей конвертации в рекурсивный конечный автомат, так и для получения его из "внешних источников", таких, например, как преобразование из стандартного внутреннего представления КС грамматик в pyformlang.
- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html), реализовать **функцию** преобразования контекстно-свободной грамматики в стандартном формате pyformlang в ECFG.
  - Предусмотреть возможность получать исходную грамматику из различных источников. Например, прочитать из файла или получить из преобразования в ОНФХ.
- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html), [регулярными выражениями](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression) и [конечными автоматами](https://pyformlang.readthedocs.io/en/latest/usage.html#finite-automata), реализовать **функцию** преобразования контекстно-свободной грамматики в ECFG в рекурсивный конечный автомат.
  - Предусмотреть возможность получать исходную грамматику из различных источников. Например, прочитать из файла, прочитать из строковой переменной, получить как результат работы какой-либо другой процедуры.
- [x] Реализовать **функцию** минимизации рекурсивного конечного автомата. Здесь под минимизацией понимается минимизация автомата для каждого нетерминала как конечного автомата над смешанным алфавитом.
- [x] Добавить необходимые тесты.

2022-11-03 21:52 UTC, artmotika commented
Тоже сделал новый pull reqeust, чтобы отобразить только нужные файлы

2022-11-08 18:58 UTC, EgorOrachyov requested changes

2022-11-08 18:58 UTC, EgorOrachyov commented on project/rsm.py
> +    #     return res_cfg
Если комментарий не является документацией - пояснением к коду, то его надо удалять

2022-11-08 18:58 UTC, EgorOrachyov commented on tests/test_ecfg.py
> +    actual_productions_str_set4.add("S -> (NP.VP)")
если у вас несколько сетов (входов), то надо на отдельные тесты разбивать
1 тест = 1 вход

2022-11-08 18:58 UTC, EgorOrachyov commented on tests/test_ecfg.py
> +    actual_productions_str_set3.add("S -> (NP.VP)")
Уменьшить дублирование, меньше правил, но больше разных кейсов. 2х достаточно было бы

2022-11-08 18:58 UTC, EgorOrachyov commented on tests/test_ecfg.py
> +def test_from_pyfl_cfg():
название тесты бы поменял чтобы чуть яснее стало что происходит

2022-11-08 23:31 UTC, artmotika commented on project/rsm.py
> +    #     return res_cfg
удалил

2022-11-08 23:33 UTC, artmotika commented on tests/test_ecfg.py
> +    actual_productions_str_set4.add("S -> (NP.VP)")
данные сеты проверяли 1 вход, так как они проверяли строки пришлось сделать несколько сетов. Поправил на более понятные Dict() с Set()

2022-11-08 23:35 UTC, artmotika commented on tests/test_ecfg.py
> +def test_from_pyfl_cfg():
добавил комментарий

2022-11-14 20:34 UTC, EgorOrachyov approved these changes

2022-11-15 13:10 UTC, closed without merging