Task 2
artmotika/formal-lang-course pull request #2
Opened 2022-09-18 20:34 UTC by artmotika

# Задача 2. Построение детерминированного конечного автомата по регулярному выражению и недетерминированного конечного автомата по графу

* **Мягкий дедлайн**: 18.09.2022, 23:59
* **Жёсткий дедлайн**: 21.09.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task1.md) (загруженный из датасета по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2022-09-19 19:12 UTC, EgorOrachyov requested changes

2022-09-19 19:12 UTC, EgorOrachyov commented on project/automata_module.py
> +from networkx.drawing.nx_pydot import read_dot
`automata_module.py` для python-файла как-то кринжово звучит (в том плане, что понятно, что этот файл -- это python модуль). Предлагаю сэкономить глифы и назвать просто `automata.py`,  или как-то иначе, но без `module`, тк смысловой нагрузки здесь это не несет.

2022-09-19 19:12 UTC, EgorOrachyov commented on project/graph_module.py
>  from networkx.drawing.nx_pydot import to_pydot
Тоже самое про `graph_module`. Лучше `graph_utilities` `graph_functions` и т.д.

2022-09-19 19:12 UTC, EgorOrachyov commented on tests/test_automata_module.py
> +from networkx.algorithms.isomorphism.isomorph import is_isomorphic
Соответсвтенно не забыть переименовать тестовые файлы.

2022-09-19 19:12 UTC, EgorOrachyov commented on tests/test_automata_module.py
> +def test_build_nfa_from_graph_from_dataset():
Начиная отсюда и ниже я бы разбил тест на 2, чтобы 
а) сократить размер файла
б) тестировать regex и nfa from graph в разных файлах, тк это по сути разные функциональные юниты

2022-09-19 19:12 UTC, EgorOrachyov commented on tests/test_graph_module.py
> -from project.graph_module import get_graph_count_vertex_edges_labels
Тоже самое тут -- переименовать файл (убираем module). Если несколько смысловых юнитов тестируется, разбить на несколько тестовых файлов.

2022-09-19 19:40 UTC, artmotika commented
Поправил

2022-09-22 10:51 UTC, EgorOrachyov approved these changes

2022-09-22 14:31 UTC, merged