Task 3
artmotika/formal-lang-course pull request #3
Opened 2022-09-25 20:49 UTC by artmotika

# Задача 3. Регулярные запросы для всех пар вершин

* **Мягкий дедлайн**: 25.09.2022, 23:59
* **Жёсткий дедлайн**: 28.09.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [x] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-09-26 18:09 UTC, EgorOrachyov requested changes
Не увидел тесты для:

- булевой декомпозиции
- для rpq запросов
- для транзитивного замыкания

2022-09-26 18:09 UTC, EgorOrachyov commented on project/BoolDecomposedFA.py
> +from pyformlang.finite_automaton import State
snake-case для модулей?

2022-09-26 18:09 UTC, EgorOrachyov commented on project/rpq.py
> +    )
1. Похоже скорее на list, а не на python, не оч читаемо
2. Я правильно понял, что тут set(... for _ in _ if _), может тогда сразу сделать через {} comprehension.

2022-09-27 01:30 UTC, artmotika commented
замечания учел. Не проходят 2 старых теста, где импортируется граф из dataset cfpq_data, то есть проблема не моя

2022-09-27 17:49 UTC, EgorOrachyov approved these changes

2022-09-27 19:37 UTC, merged