Task 4
artmotika/formal-lang-course pull request #4
Opened 2022-10-02 20:48 UTC by artmotika

# Задача 4. Регулярные запросы для нескольких стартовых вершин

* **Мягкий дедлайн**: 02.10.2022, 23:59
* **Жёсткий дедлайн**: 05.10.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [x] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-10-03 19:19 UTC, EgorOrachyov requested changes
Нет тестов к написанной функциональности

2022-10-06 08:01 UTC, EgorOrachyov requested changes

2022-10-06 08:01 UTC, EgorOrachyov commented on project/rpq.py
> +                *bool_decomposed_aut1.get_bfs_intersection(
На лицо явное дублирование кода. 

Идея сделать параметризацию метода rpq через тип запроса хорошая. Но надо пойти было дальше.
Можно передавать в качестве аргумента объект, у которого будут методы интерфейсные. Каждый алгоритм их по своему реализует. Далее тут просто дергаете эти методы. Своего рода паттерн стратегия + билдер.

Флоу очень повторяется: у вас есть общие щаги
1. граф и запрос to автоматы
2. пересечь, объединить и тд
3. фильтрация результата
4. подготовка ответа

Да общие шаги оставить в rpq, детали вынести в интерфейс и для каждого алгоритма отдельно реализовать

2022-10-07 13:47 UTC, artmotika commented on project/rpq.py
> +                *bool_decomposed_aut1.get_bfs_intersection(
Я сделал так: передаю тип метода и уже в rpq преобразую graph и regex в автоматы и там, в rpq, создаю объекты-билдеры. А если сразу передавать объекты-билдеры в rpq, то не понятно что в них передавать, так как именно в rpq  graph и regex переводятся в автоматы

2022-10-08 11:13 UTC, EgorOrachyov approved these changes

2022-10-08 14:04 UTC, merged